service:
  name: slackonymous

frameworkVersion: "~1.26"

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-1

functions:
  anonymous:
    handler: handler.anonymous
    events:
      - http:
          method: get
          path: anonymous
      - http:
          method: post
          path: anonymous
