service:
  name: slackonymous

frameworkVersion: "~1.26"

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
